### ISSUE TITLE
LUA Error in new Cata Classic

### ISSUE THREAD

**Issue by dblanch369** [nebularg/BetterAddonList#2]
Getting this error after Cata launch....

9x BetterAddonList/BetterAddonList.lua:727: hooksecurefunc(): AddonList_InitButton is not a function
[string "=[C]"]: in function `hooksecurefunc'
[string "@BetterAddonList/BetterAddonList.lua"]:727: in main chunk

Locals:

**Comment by nebularg** [comment]
Thanks, pushed a new version so Cata loads the correct file
