### ISSUE TITLE
"Disable All" button also disables BetterAddonList.

### ISSUE THREAD

**Issue by Kolmarwow** [nebularg/BetterAddonList#3]
When you click the "Disable All" button on the addon list it also disables BetterAddonList, which previously wasn't the case.

This is a duplicate of an issue listed on [Curseforge](https://legacy.curseforge.com/wow/addons/betteraddonlist/issues) but I'm not sure if that tracker is being checked so reposting here.

**Comment by nebularg** [comment]
Thanks, Looks like https://github.com/nebularg/BetterAddonList/pull/5 fixed this by using the updated addon APIs directly
